//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docgia
    {
        public Docgia()
        {
            this.Muontras = new HashSet<Muontra>();
        }
    
        public int ma_docgia { get; set; }
        public string ten_docgia { get; set; }
        public string diachi { get; set; }
        public string sothe { get; set; }
    
        public virtual Thethuvien Thethuvien { get; set; }
        public virtual ICollection<Muontra> Muontras { get; set; }
    }
}
