//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muontra
    {
        public string ma_muontra { get; set; }
        public Nullable<int> ma_docgia { get; set; }
        public string ma_sach { get; set; }
        public System.DateTime ngaymuon { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
        public bool datra { get; set; }
        public string ghichu { get; set; }
        public string ngaymuon_hienthi { get; set; }
        public string ngaytra_hienthi { get; set; }
    
        public virtual Docgia Docgia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
