//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhaxuatban
    {
        public Nhaxuatban()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public string ma_nhaxuatban { get; set; }
        public string ten_nhaxuatban { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string nguoidaidien { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
