//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.Muontras = new HashSet<Muontra>();
        }
    
        public string ma_sach { get; set; }
        public string ten_sach { get; set; }
        public string ma_theloai { get; set; }
        public string ma_nhaxuatban { get; set; }
    
        public virtual ICollection<Muontra> Muontras { get; set; }
        public virtual Nhaxuatban Nhaxuatban { get; set; }
        public virtual Theloai Theloai { get; set; }
    }
}
