//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theloai
    {
        public Theloai()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public string ma_theloai { get; set; }
        public string ten_theloai { get; set; }
        public string ghichu { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
